version: "3.3"  # optional since v1.27.0
services:
  api:
    build:
        context: .
        dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/code

  frontend:
    build:
        context: .
        dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/front
